"""
Integration tests for basic panel XML features.

Tests fundamental panel creation, ID assignment, transforms, hierarchy,
and variable system through the complete parsing and layout pipeline.
"""

import unittest
import numpy as np
from gxml_layout import GXMLLayout
from gxml_types import Axis
import mathutils.gxml_math as GXMLMath
from layouts.gxml_construct_layout import GXMLConstructLayout
from layouts.gxml_stack_layout import GXMLStackLayout
from layouts.gxml_fixed_layout import GXMLFixedLayout
from tests.test_fixtures.base_integration_test import BaseIntegrationTest
from tests.test_fixtures.assertions import assert_corner_points
from tests.test_fixtures.xml_integration_test_tools import XMLIntegrationTestValidator


class PanelBasicXMLTests(BaseIntegrationTest):
    """Integration tests for basic panel XML features.
    
    Tests fundamental panel creation, ID assignment, transforms, and
    basic attribute parsing through the complete pipeline.
    """
    
    def setUp(self):
        super().setUp()
        GXMLLayout.bind_layout("construct", GXMLConstructLayout())
        GXMLLayout.bind_layout("stack", GXMLStackLayout())
        GXMLLayout.bind_layout("fixed", GXMLFixedLayout())
    
    def testDefaultPanel(self):
        """Test default panel gets correct initial state."""
        xml_input = """<root><panel/></root>
        """

        expected_xml = """<root>
            <r id="0" pts="0,0,0|1,0,0|1,1,0|0,1,0"/>
        </root>
        """

        self.assertXMLOutput(xml_input, expected_xml)
    
    def testPanelWindingOrder(self):
        """Test panel corners follow correct winding order."""
        xml_input = """<root><panel/></root>
        """

        expected_xml = """<root>
            <r id="0" pts="0,0,0|1,0,0|1,1,0|0,1,0"/>
        </root>
        """

        self.assertXMLOutput(xml_input, expected_xml)
        
    def testAutoGeneratedIds(self):
        """Test panels get auto-generated sequential IDs when not specified."""
        
        xml_input = """
        <root>
            <panel/>
            <panel/>
            <panel/>
        </root>
        """

        expected_xml = """
        <root>
            <r id="0"/>
            <r id="1"/>
            <r id="2"/>
        </root>
        """

        self.assertXMLOutput(xml_input, expected_xml)
        
    def testMixedExplicitAndAutoIds(self):
        """Test explicit IDs are preserved and auto IDs skip used values."""
        panels = self.parsePanel('''
            <root>
                <panel id="my"/>
                <panel/>
                <panel id="panelid"/>
                <panel/>
            </root>''').children
        
        self.assertEqual(panels[0].id, "my")
        self.assertEqual(panels[1].id, "1")
        self.assertEqual(panels[2].id, "panelid")
        self.assertEqual(panels[3].id, "3")
    
    def testDuplicateIdRaisesError(self):
        """Test duplicate IDs are rejected."""
        with self.assertRaises(ValueError):
            self.parsePanel('''<root><panel id="dup"/><panel id="dup"/></root>''')
    
    def testTransformAttributes(self):
        """Test size, rotate, and pivot attributes create correct transform."""
        xml_input = """<root>
            <panel size="3,3" rotate="0,45" pivot="0.5,0.5"/>
        </root>
        """

        expected_xml = """<root>
            <r id="0" pts="-1.06066,-1.5,1.06066|1.06066,-1.5,-1.06066|1.06066,1.5,-1.06066|-1.06066,1.5,1.06066"/>
        </root>
        """

        self.assertXMLOutput(xml_input, expected_xml)
    
    def testTransformWithEmbeddedExpressions(self):
        """Test attribute values can contain Python expressions."""
        xml_input = """<root>
            <panel size="1+2,4-1" rotate="0,20*2+5" pivot="1/2,2/4"/>
        </root>
        """

        expected_xml = """<root>
            <r id="0" pts="-1.06066,-1.5,1.06066|1.06066,-1.5,-1.06066|1.06066,1.5,-1.06066|-1.06066,1.5,1.06066"/>
        </root>
        """

        self.assertXMLOutput(xml_input, expected_xml)
    
    def testZeroScale(self):
        """Test zero-scale panels degenerate correctly."""
        xml_input = """<root>
            <panel size="0,0,0"/>
        </root>
        """

        expected_xml = """<root>
            <r id="0" pts="0,0,0|0,0,0|0,0,0|0,0,0"/>
        </root>
        """

        self.assertXMLOutput(xml_input, expected_xml)
        
    def testZeroScaleRotated(self):
        """Test zero-scale rotated panels degenerate correctly."""
        xml_input = """<root>
            <panel rotate="0,90,0" size="2,0,0" pivot="0.5,0.5"/>
        </root>
        """

        expected_xml = """<root>
            <r id="0" pts="-6.12323e-17,0,1|6.12323e-17,0,-1|6.12323e-17,0,-1|-6.12323e-17,0,1"/>
        </root>
        """

        self.assertXMLOutput(xml_input, expected_xml)


class PanelHierarchyXMLTests(BaseIntegrationTest):
    """Integration tests for panel hierarchy and relationships.
    
    Tests parent-child relationships and coordinate transformations.
    """
    
    def setUp(self):
        super().setUp()
        GXMLLayout.bind_layout("construct", GXMLConstructLayout())
        GXMLLayout.bind_layout("stack", GXMLStackLayout())
        GXMLLayout.bind_layout("fixed", GXMLFixedLayout())
    
    def testParentRelationships(self):
        """Test parent references are correctly established."""
        xml_input = """<root>
            <panel>
                <panel/>
            </panel>
        </root>
        """

        # Inner panel is laid out with the stack layout which is what produces the offset
        expected_xml = """<root>
            <r id="0" pts="0,0,0|1,0,0|1,1,0|0,1,0">
                <r id="0" pts="0.25,0.25,0|0.75,0.25,0|0.75,0.75,0|0.25,0.75,0"/>
            </r>
        </root>
        """

        self.assertXMLOutput(xml_input, expected_xml)
    
    def testZeroScalePanelDoesNotCrash(self):
        """Test zero-scale panels don't cause crashes."""
        xml_input = """<root>
            <panel size="5,5,5"/>
            <panel size="0,0,0"/>
        </root>
        """

        expected_xml = """<root>
            <r id="0" pts="0,0,0|5,0,0|5,5,0|0,5,0"/>
            <r id="1" pts="5,0,0|5,0,0|5,0,0|5,0,0"/>
        </root>
        """

        self.assertXMLOutput(xml_input, expected_xml)

class PanelVariablesXMLTests(BaseIntegrationTest):
    """Integration tests for variable system in XML.
    
    Tests parsing and using variables defined in <vars> blocks.
    """
    
    def setUp(self):
        super().setUp()
        GXMLLayout.bind_layout("construct", GXMLConstructLayout())
        GXMLLayout.bind_layout("stack", GXMLStackLayout())
        GXMLLayout.bind_layout("fixed", GXMLFixedLayout())
    
    def testVarsInRoot(self):
        """Test variables defined in root are accessible in attributes."""
        xml_input = """<root>
            <vars>
                <w>2</w>
            </vars>
            <panel size="w"/>
        </root>
        """

        expected_xml = """<root>
            <r id="0" pts="0,0,0|2,0,0|2,1,0|0,1,0"/>
        </root>
        """

        self.assertXMLOutput(xml_input, expected_xml)


if __name__ == '__main__':
    unittest.main()
